import type { Metadata } from "next";
import "./globals.css";
import { ProgressProvider } from "@/provider/ProgressProvider";
import { ThemeProvider } from "@/provider/theme-provider";
import QueryClientProviderMain from "@/provider/QueryClientProvider";

export const metadata: Metadata = {
  title: "Docker Inspect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ProgressProvider>
            <QueryClientProviderMain>
              {children}
            </QueryClientProviderMain>
          </ProgressProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
